plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.radardarede.sensor'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.radardarede.sensor'
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName '0.1.0-probe'
    }

    buildTypes {
        debug {
            minifyEnabled false
            buildConfigField 'boolean', 'PROBE_MODE', 'true'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField 'boolean', 'PROBE_MODE', 'false'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
